DROP TABLE OPERAZIONE IF EXISTS;
CREATE TABLE OPERAZIONE (
ID_OPERAZIONE INTEGER PRIMARY KEY AUTO_INCREMENT,
LUOGO VARCHAR(25),
TIPO VARCHAR(25),
IMPORTO DECIMAL,
DATA DATE,
ORA TIME,
ID_CARTA INTEGER
);

DROP TABLE CARTA_DI_CREDITO IF EXISTS;
CREATE TABLE CARTA_DI_CREDITO (
ID_CARTA_DI_CREDITO INTEGER PRIMARY KEY,
IBAN VARCHAR(25),
USERNAME_UTENTE VARCHAR(25)
);

DROP TABLE RUOLI IF EXISTS;
CREATE TABLE RUOLI (
ID_RUOLO INTEGER PRIMARY KEY AUTO_INCREMENT,
USERNAME_RUOLO VARCHAR(25),
RUOLO VARCHAR(25)
);

DROP TABLE UTENTE IF EXISTS;
CREATE TABLE UTENTE ( 
USERNAME VARCHAR(25) PRIMARY KEY,
PASSWORD VARCHAR(25),
ENABLED BOOLEAN, 
NOME VARCHAR(25), 
COGNOME VARCHAR(25) 
);